#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check ESLint Standards
yarn lint ||
(
    echo '💢🛑💢 Get that weak shit out of here! 💢🛑💢 
          ESLint Check Failed. Please run 🔨yarn lint:fix🔨 or 🔨npm run lint:fix🔨 and try to commit again.'
    false; 
)

# Check Prettier Code Format
# yarn prettier ||
# (
#     echo '💢🛑💢 Get that weak shit out of here! 💢🛑💢 
#           Prettier Code Format Failed. Please run 🔨yarn prettier:fix🔨 or 🔨npm run prettier:fix🔨 and try to commit again.'
#     false; 
# )

# If everything passes... Now we can commit
echo '✅✅✅ You win this time... I am committing this now. ✅✅✅'
